---
- name: Play to automate partition creation and managing storage with Logical Volume Manager (LVM) and create a filesystem.
  hosts: all
  become: true
  vars: 
    device: /dev/sdc
  tasks:
    - name: Create Partitions
      parted:
        device: "{{device}}"
        number: 1
        flags: [ lvm ]
        state: present
        part_end: 15GB